mysite/accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('sign_in/', views.SignInView.as_view(), name='sign_in'),
    path('sign_out/', views.SignOutView.as_view(), name='sign_out'),

 #   path('', views.IndexView.as_view(), name='index'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('super/', views.SuperOnlyView.as_view(), name='super_only'),

    path("sub/<int:i>/", views.SubPageView.as_view(), name='subpage'),
]

mysite/cars/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import index
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('', index, name='index'),
    path("cars/", include("cars.urls")),
    path("schedule/", include("schedule.urls")),
    path("uppermenu/", include("uppermenu.urls")),
    path("clients/", include("clients.urls")),
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),

    ]

mysite/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}
    Accounts | {{ block.super }}
{% endblock %}

{% block body %}
    <main class="py-5">
        <div class="container content">
            <h1>Welcome!</h1>
            <p class="lead">
                This is an example website for
                <a href="https://github.com/jazzband/django-simple-menu">django-simple-menu</a>.
            </p>
            <section>
                <h2>How to use this example</h2>
                <ol>
                    <li>
                        Create a superuser:
                        <code class="user-select-all">python3 manage.py
                            createsuperuser --username "admin"</code>
                    </li>
                    <li>
                        Create another superuser:
                        <code class="user-select-all">python3 manage.py
                            createsuperuser --username "guest"</code>
                    </li>
                    <li>
                        Log in as <code>admin</code> into
                        <a href="/admin">Django administration</a>
                        and remove admin and staff rights from
                        <code>guest</code>.
                    </li>
                    <li>
                        Try logging in and out on the website and visit
                        the pages in the top menu.
                    </li>
                </ol>
            </section>
            <section>
                <h2>More</h2>
                <ul>
                    <li>
                        <i class="bi bi-journal-code"></i>
                        <a href="https://django-simple-menu.readthedocs.io/">
                            Documentation
                        </a>
                    </li>
                    <li>
                        <i class="bi bi-github"></i>
                        <a href="https://github.com/jazzband/django-simple-menu">
                            Source code
                        </a>
                    </li>
                </ul>
            </section>
        </div>
    </main>
{% endblock %}

mysite/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
    Your profile | {{ block.super }}
{% endblock %}

{% block body %}
    <main class="py-5">
        <section class="container">
            <h1>{{ request.user.get_full_name|default:"" }}
                (@{{ request.user.username }})</h1>
            <p>
                <strong>E-Mail:</strong> {{ request.user.email }}
            </p>
        </section>
        <section class="container content">
            <p>
                The menu item for this page is being shown to everyone,
                who is authenticated:
            </p>
            <pre><code>Menu.add_item("user", MenuItem(profile_title,
                               reverse('accounts:profile'),
                               icon='person-circle',
                               <mark>check=lambda r: r.user.is_authenticated</mark>))</code></pre>
            <p>
                Also take a look at the <code>profile_title</code>. It's not a string,
                but a callable, which accepts the request object. In our case,
                it renders the user's name on the button:
            </p>
            <pre><code>def profile_title(request):
    name = request.user.get_full_name() or request.user
    return f"{name}'s Profile"</code></pre>
        </section>
    </main>
{% endblock %}

mysite/accounts/templates/accounts/sign_in.html
{% extends 'base.html' %}

{% block title %}
    Sign in | {{ block.super }}
{% endblock %}

{% block body %}
    <main class="p-4">
        <section class="container w-25 mx-auto mb-5">
            <form action="{% url 'accounts:sign_in' %}" method="post">
                {% csrf_token %}
                <h1>Sign in</h1>

                <div class="mb-3">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username"
                           name="username" autofocus>
                </div>
                <div class="mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control"
                           id="password" name="password">
                </div>

                <button class="btn btn-lg btn-primary" type="submit">
                    Sign in
                </button>
            </form>
        </section>
        <section class="container content">
            The menu item for this page is being shown to everyone,
            who is not authenticated:
            <pre><code>Menu.add_item("user", MenuItem("Sign in",
                               reverse('accounts:sign_in'),
                               icon='box-arrow-in-right',
                               <mark>check=lambda r: not r.user.is_authenticated</mark>))</code></pre>
        </section>
    </main>
{% endblock %}

mysite/accounts/templates/accounts/subpage.html
{% extends 'base.html' %}

{% block title %}
    Subpage | {{ block.super }}
{% endblock %}

{% block body %}
    <main class="py-5">
        <section class="container">
            <h1>This is a subpage</h1>
        </section>
        <section class="container content">
            <p>
                There are three identical pages that are nested inside their
                parent menu item:
            </p>
            <pre><code>submenu_items = [...]
Menu.add_item("user", MenuItem("Subpages",
                               reverse('accounts:subpage', kwargs={'i': 1}),
                               icon="menu-app",
                               <mark>children=submenu_items</mark>))</code></pre>
            <p>
                Note that the second navigation bar is only shown for the pages
                that have a submenu. You can check it in the template:
            </p>
            <pre><code>&lbrace;% <mark>if has_submenu</mark>
    &lt;!-- display submenu --&gt;
&lbrace;% endif %}</code></pre>

            <p>
                By default, the parent will not be marked active if their child
                active. The example site changes this behavior using a setting:
            </p>
            <pre><code>MENU_SELECT_PARENTS = True</code></pre>
        </section>
    </main>
{% endblock %}

mysite/accounts/templates/accounts/super_only.html
{% extends 'base.html' %}

{% block title %}
    Secret page | {{ block.super }}
{% endblock %}

{% block body %}
    <main class="py-5">
        <section class="container">
            <h1>Shhh!.. This is a secret page</h1>
        </section>
        <section class="container content">
            <p>
            The menu item for this page is being shown only to superusers:
            </p>
            <pre><code>Menu.add_item("user", MenuItem("Secret superuser page",
                               reverse("accounts:super_only"),
                               icon='incognito',
                               <mark>check=lambda r: r.user.is_superuser</mark>))</code></pre>
        </section>
    </main>
{% endblock %}